# MySQL 루트 비밀번호를 저장하는 Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ceph-storage
type: Opaque
data:
  # MySQL Root 비밀번호 (base64 인코딩됨)
  # echo -n "kosa1004" | base64 -> a29zYTEwMDQ=
  MYSQL_ROOT_PASSWORD: a29zYTEwMDQ=
